#!/bin/sh

#fix for slow app launching
#systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
#hash dbus-update-activation-environment 2>/dev/null && \
#	dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

#output manager
way-displays > /tmp/way-displays.${XDG_VTNR}.${USER}.log 2>&1 &

#random wallpaper script
swww init
/home/emma/.dotfiles/lapwall.sh

#startup programs
#pipewire &
#wireplumber &
easyeffects --gapplication-service &
dunst &
udiskie &
chronyd &

#protonvpn requirements
gnome-keyring-daemon --start &
nm-applet --sm-disable &

#bar
waybar &

#startup hotkey daemon
#swhks &
#pkexec swhkd &
source /home/emma/.dotfiles/river_lap/keybinds.sh

#input configuration
riverctl keyboard-layout -options ctrl:swapcaps -variant dvorak us

#window rules
riverctl rule-add csd -app-id "bar"

#colours
source /home/emma/.dotfiles/river/mocha.conf

riverctl background-color $base
riverctl border-color-unfocused $mantle
riverctl border-color-focused $teal
riverctl border-color-urgent $teal
riverctl border-width 2

#tiling daemon
riverctl default-layout rivertile
riverctl attach-mode bottom
rivertile -view-padding 4 -outer-padding 4
