#!/bin/sh

#fix for slow app launching
systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
hash dbus-update-activation-environment 2>/dev/null && \
	dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

#output manager
kanshi &

#bar
waybar &

#startup programs
pipewire &
wireplumber &
dunst &
udiskie &
chronyd &

#random wallpaper script
swww init
/home/emma/.dotfiles/deskwall.sh

#startup hotkey daemon
swhks &
pkexec swhkd &

#input configuration
riverctl input pointer-5426-123-Razer_Razer_Viper_Ultimate_Dongle accel-profile flat
riverctl input pointer-5426-123-Razer_Razer_Viper_Ultimate_Dongle pointer-accel 0.0

#tiling daemon
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6
